/*
DROP SEQUENCE [sq_AppBinaryFiles]
DROP SEQUENCE [sq_AppMainTree]
DROP SEQUENCE [sq_AppIType]
DROP SEQUENCE [sq_AppDBNames]
DROP SEQUENCE [sq_AppDataSets]
DROP SEQUENCE [sq_AppGlobalParameters]
DROP SEQUENCE [sq_AppGridColors]
DROP SEQUENCE [sq_AppColumns]
DROP SEQUENCE [sq_AppCmdParams]
DROP SEQUENCE [sq_AppCmd]
DROP SEQUENCE [sq_AppDialogControls]
DROP SEQUENCE [sq_AppDialogDetailTables]
DROP SEQUENCE [sq_AppDialogsLayoutFlags]
DROP SEQUENCE [sq_AppDialogsLayout]
DROP SEQUENCE [sq_AppDialogs]
DROP SEQUENCE [sq_AppPlugins]
DROP SEQUENCE [sq_AppReportsDataSets]
DROP SEQUENCE [sq_AppReportsParams]
DROP SEQUENCE [sq_AppReports]
DROP SEQUENCE [sq_AppScriptsParams]
DROP SEQUENCE [sq_AppScripts]
DROP SEQUENCE [sq_AppTemplatesData]
DROP SEQUENCE [sq_AppTemplatesDataSets]
DROP SEQUENCE [sq_AppTemplates]
DROP SEQUENCE [sq_dfPathFolderActions]
DROP SEQUENCE [sq_dfPathFolderRules]
DROP SEQUENCE [sq_dfMethods]
DROP SEQUENCE [sq_dfPathFolders]
DROP SEQUENCE [sq_dfTypes]
DROP SEQUENCE [sq_dfClasses]
DROP SEQUENCE [sq_dfActionsMessages]
DROP SEQUENCE [sq_AppPluginsCommonCmd]

*/
CREATE SEQUENCE [sq_AppBinaryFiles]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppMainTree]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppIType]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppDBNames]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppDataSets]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppGlobalParameters]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppGridColors]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppColumns]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppCmdParams]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppCmd]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppDialogControls]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppDialogDetailTables]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppDialogsLayoutFlags]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppDialogsLayout]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppDialogs]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppPlugins]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppPluginsCommonCmd]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppReportsDataSets]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppReportsParams]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppReports]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppScriptsParams]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppScripts]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppTemplatesData]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppTemplatesDataSets]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_AppTemplates]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
--DocFlow
CREATE SEQUENCE [sq_dfPathFolderActions]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_dfPathFolderRules]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_dfMethods]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_dfPathFolders]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_dfTypes]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_dfClasses]  AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1
CREATE SEQUENCE [sq_dfActionsMessages] AS [int] START WITH 1 INCREMENT BY 1 MINVALUE 1


GO


