DECLARE @Tmp TABLE
(
[Code] VARCHAR(3) UNIQUE,
[Alfa3] VARCHAR(3) UNIQUE,
[FullName] VARCHAR(255)
)

INSERT INTO @Tmp VALUES ('643','RUB','Российский рубль')
INSERT INTO @Tmp VALUES ('810','RUR','Российский рубль')
INSERT INTO @Tmp VALUES ('840','USD','Доллар США')
INSERT INTO @Tmp VALUES ('978','EUR','Евро')
INSERT INTO @Tmp VALUES ('980','UAH','Гривна')
INSERT INTO @Tmp VALUES ('398','KZT','Тенге')
INSERT INTO @Tmp VALUES ('764','THB','Бат')
INSERT INTO @Tmp VALUES ('934','TMT','Новый туркменский манат')
INSERT INTO @Tmp VALUES ('860','UZS','Узбекский сум')
INSERT INTO @Tmp VALUES ('008','ALL','Лек')
INSERT INTO @Tmp VALUES ('012','DZD','Алжирский динар')
INSERT INTO @Tmp VALUES ('032','ARS','Аргентинское песо')
INSERT INTO @Tmp VALUES ('036','AUD','Австралийский доллар')
INSERT INTO @Tmp VALUES ('044','BSD','Багамский доллар')
INSERT INTO @Tmp VALUES ('048','BHD','Бахрейнский динар')
INSERT INTO @Tmp VALUES ('050','BDT','Така')
INSERT INTO @Tmp VALUES ('051','AMD','Армянский драм')
INSERT INTO @Tmp VALUES ('052','BBD','Барбадосский доллар')
INSERT INTO @Tmp VALUES ('060','BMD','Бермудский доллар')
INSERT INTO @Tmp VALUES ('064','BTN','Нгултрум')
INSERT INTO @Tmp VALUES ('068','BOB','Боливиано')
INSERT INTO @Tmp VALUES ('072','BWP','Пула')
INSERT INTO @Tmp VALUES ('084','BZD','Белизский доллар')
INSERT INTO @Tmp VALUES ('090','SBD','Доллар Соломоновых Островов')
INSERT INTO @Tmp VALUES ('096','BND','Брунейский доллар')
INSERT INTO @Tmp VALUES ('104','MMK','Кьят')
INSERT INTO @Tmp VALUES ('108','BIF','Бурундийский франк')
INSERT INTO @Tmp VALUES ('116','KHR','Риель')
INSERT INTO @Tmp VALUES ('124','CAD','Канадский доллар')
INSERT INTO @Tmp VALUES ('132','CVE','Эскудо Кабо-Верде')
INSERT INTO @Tmp VALUES ('136','KYD','Доллар Островов Кайман')
INSERT INTO @Tmp VALUES ('144','LKR','Шри-ланкийская рупия')
INSERT INTO @Tmp VALUES ('152','CLP','Чилийское песо')
INSERT INTO @Tmp VALUES ('156','CNY','Юань')
INSERT INTO @Tmp VALUES ('170','COP','Колумбийское песо')
INSERT INTO @Tmp VALUES ('174','KMF','Франк Комор')
INSERT INTO @Tmp VALUES ('188','CRC','Костариканский колон')
INSERT INTO @Tmp VALUES ('191','HRK','Куна')
INSERT INTO @Tmp VALUES ('192','CUP','Кубинское песо')
INSERT INTO @Tmp VALUES ('203','CZK','Чешская крона')
INSERT INTO @Tmp VALUES ('208','DKK','Датская крона')
INSERT INTO @Tmp VALUES ('214','DOP','Доминиканское песо')
INSERT INTO @Tmp VALUES ('222','SVC','Сальвадорский колон')
INSERT INTO @Tmp VALUES ('230','ETB','Эфиопский быр')
INSERT INTO @Tmp VALUES ('232','ERN','Накфа')
INSERT INTO @Tmp VALUES ('238','FKP','Фунт Фолклендских Островов')
INSERT INTO @Tmp VALUES ('242','FJD','Доллар Фиджи')
INSERT INTO @Tmp VALUES ('262','DJF','Франк Джибути')
INSERT INTO @Tmp VALUES ('270','GMD','Даласи')
INSERT INTO @Tmp VALUES ('292','GIP','Гибралтарский фунт')
INSERT INTO @Tmp VALUES ('320','GTQ','Кетсаль')
INSERT INTO @Tmp VALUES ('324','GNF','Гвинейский франк')
INSERT INTO @Tmp VALUES ('328','GYD','Гайанский доллар')
INSERT INTO @Tmp VALUES ('332','HTG','Гурд')
INSERT INTO @Tmp VALUES ('340','HNL','Лемпира')
INSERT INTO @Tmp VALUES ('344','HKD','Гонконгский доллар')
INSERT INTO @Tmp VALUES ('348','HUF','Форинт')
INSERT INTO @Tmp VALUES ('352','ISK','Исландская крона')
INSERT INTO @Tmp VALUES ('356','INR','Индийская рупия')
INSERT INTO @Tmp VALUES ('360','IDR','Рупия')
INSERT INTO @Tmp VALUES ('364','IRR','Иранский риал')
INSERT INTO @Tmp VALUES ('368','IQD','Иракский динар')
INSERT INTO @Tmp VALUES ('376','ILS','Новый израильский шекель')
INSERT INTO @Tmp VALUES ('388','JMD','Ямайский доллар')
INSERT INTO @Tmp VALUES ('392','JPY','Иена')
INSERT INTO @Tmp VALUES ('400','JOD','Иорданский динар')
INSERT INTO @Tmp VALUES ('404','KES','Кенийский шиллинг')
INSERT INTO @Tmp VALUES ('408','KPW','Северокорейская вона')
INSERT INTO @Tmp VALUES ('410','KRW','Вона')
INSERT INTO @Tmp VALUES ('414','KWD','Кувейтский динар')
INSERT INTO @Tmp VALUES ('417','KGS','Сом')
INSERT INTO @Tmp VALUES ('418','LAK','Кип')
INSERT INTO @Tmp VALUES ('422','LBP','Ливанский фунт')
INSERT INTO @Tmp VALUES ('426','LSL','Лоти')
INSERT INTO @Tmp VALUES ('430','LRD','Либерийский доллар')
INSERT INTO @Tmp VALUES ('434','LYD','Ливийский динар')
INSERT INTO @Tmp VALUES ('446','MOP','Патака')
INSERT INTO @Tmp VALUES ('454','MWK','Квача')
INSERT INTO @Tmp VALUES ('458','MYR','Малайзийский ринггит')
INSERT INTO @Tmp VALUES ('462','MVR','Руфия')
INSERT INTO @Tmp VALUES ('480','MUR','Маврикийская рупия')
INSERT INTO @Tmp VALUES ('484','MXN','Мексиканское песо')
INSERT INTO @Tmp VALUES ('496','MNT','Тугрик')
INSERT INTO @Tmp VALUES ('498','MDL','Молдавский лей')
INSERT INTO @Tmp VALUES ('504','MAD','Марокканский дирхам')
INSERT INTO @Tmp VALUES ('512','OMR','Оманский риал')
INSERT INTO @Tmp VALUES ('516','NAD','Доллар Намибии')
INSERT INTO @Tmp VALUES ('524','NPR','Непальская рупия')
INSERT INTO @Tmp VALUES ('532','ANG','Нидерландский антильский гульден')
INSERT INTO @Tmp VALUES ('533','AWG','Арубанский флорин')
INSERT INTO @Tmp VALUES ('548','VUV','Вату')
INSERT INTO @Tmp VALUES ('554','NZD','Новозеландский доллар')
INSERT INTO @Tmp VALUES ('558','NIO','Золотая кордоба')
INSERT INTO @Tmp VALUES ('566','NGN','Найра')
INSERT INTO @Tmp VALUES ('578','NOK','Норвежская крона')
INSERT INTO @Tmp VALUES ('586','PKR','Пакистанская рупия')
INSERT INTO @Tmp VALUES ('590','PAB','Бальбоа')
INSERT INTO @Tmp VALUES ('598','PGK','Кина')
INSERT INTO @Tmp VALUES ('600','PYG','Гуарани')
INSERT INTO @Tmp VALUES ('604','PEN','Новый соль')
INSERT INTO @Tmp VALUES ('608','PHP','Филиппинское песо')
INSERT INTO @Tmp VALUES ('634','QAR','Катарский риал')
INSERT INTO @Tmp VALUES ('646','RWF','Франк руанды')
INSERT INTO @Tmp VALUES ('654','SHP','Фунт Святой Елены')
INSERT INTO @Tmp VALUES ('682','SAR','Саудовский риял')
INSERT INTO @Tmp VALUES ('690','SCR','Сейшельская рупия')
INSERT INTO @Tmp VALUES ('694','SLL','Леоне')
INSERT INTO @Tmp VALUES ('702','SGD','Сингапурский доллар')
INSERT INTO @Tmp VALUES ('704','VND','Донг')
INSERT INTO @Tmp VALUES ('706','SOS','Сомалийский шиллинг')
INSERT INTO @Tmp VALUES ('710','ZAR','Рэнд')
INSERT INTO @Tmp VALUES ('728','SSP','Южносуданский фунт')
INSERT INTO @Tmp VALUES ('748','SZL','Лилангени')
INSERT INTO @Tmp VALUES ('752','SEK','Шведская крона')
INSERT INTO @Tmp VALUES ('756','CHF','Швейцарский франк')
INSERT INTO @Tmp VALUES ('760','SYP','Сирийский фунт')
INSERT INTO @Tmp VALUES ('776','TOP','Паанга')
INSERT INTO @Tmp VALUES ('780','TTD','Доллар Тринидада и Тобаго')
INSERT INTO @Tmp VALUES ('784','AED','Дирхам (ОАЭ)')
INSERT INTO @Tmp VALUES ('788','TND','Тунисский динар')
INSERT INTO @Tmp VALUES ('800','UGX','Угандийский шиллинг')
INSERT INTO @Tmp VALUES ('807','MKD','Денар')
INSERT INTO @Tmp VALUES ('818','EGP','Египетский фунт')
INSERT INTO @Tmp VALUES ('826','GBP','Фунт стерлингов')
INSERT INTO @Tmp VALUES ('834','TZS','Танзанийский шиллинг')
INSERT INTO @Tmp VALUES ('858','UYU','Уругвайское песо')
INSERT INTO @Tmp VALUES ('882','WST','Тала')
INSERT INTO @Tmp VALUES ('886','YER','Йеменский риал')
INSERT INTO @Tmp VALUES ('901','TWD','Новый тайваньский доллар')
INSERT INTO @Tmp VALUES ('928','VES','БОЛИВАР СОБЕРАНО')
INSERT INTO @Tmp VALUES ('929','MRU','УГИЯ')
INSERT INTO @Tmp VALUES ('930','STN','ДОБРА')
INSERT INTO @Tmp VALUES ('931','CUC','Конвертируемое песо')
INSERT INTO @Tmp VALUES ('932','ZWL','Доллар Зимбабве')
INSERT INTO @Tmp VALUES ('933','BYN','БЕЛОРУССКИЙ РУБЛЬ')
INSERT INTO @Tmp VALUES ('936','GHS','Ганский седи')
INSERT INTO @Tmp VALUES ('938','SDG','Суданский фунт')
INSERT INTO @Tmp VALUES ('940','UYI','Уругвайское песо в индексированных единицах')
INSERT INTO @Tmp VALUES ('941','RSD','Сербский динар')
INSERT INTO @Tmp VALUES ('943','MZN','Мозамбикский метикал')
INSERT INTO @Tmp VALUES ('944','AZN','Азербайджанский манат')
INSERT INTO @Tmp VALUES ('946','RON','Румынский лей')
INSERT INTO @Tmp VALUES ('949','TRY','Турецкая лира')
INSERT INTO @Tmp VALUES ('950','XAF','Франк КФА ВЕАС')
INSERT INTO @Tmp VALUES ('951','XCD','Восточно-карибский доллар')
INSERT INTO @Tmp VALUES ('952','XOF','Франк КФА ВСЕАО')
INSERT INTO @Tmp VALUES ('953','XPF','Франк КФП')
INSERT INTO @Tmp VALUES ('960','XDR','СДР (специальные права заимствования)')
INSERT INTO @Tmp VALUES ('967','ZMW','Замбийская квача')
INSERT INTO @Tmp VALUES ('968','SRD','Суринамский доллар')
INSERT INTO @Tmp VALUES ('969','MGA','Малагасийский ариари')
INSERT INTO @Tmp VALUES ('970','COU','Единица реальной стоимости')
INSERT INTO @Tmp VALUES ('971','AFN','Афгани')
INSERT INTO @Tmp VALUES ('972','TJS','Сомони')
INSERT INTO @Tmp VALUES ('973','AOA','Кванза')
INSERT INTO @Tmp VALUES ('975','BGN','Болгарский лев')
INSERT INTO @Tmp VALUES ('976','CDF','Конголезский франк')
INSERT INTO @Tmp VALUES ('977','BAM','Конвертируемая марка')
INSERT INTO @Tmp VALUES ('981','GEL','Лари')
INSERT INTO @Tmp VALUES ('985','PLN','Злотый')
INSERT INTO @Tmp VALUES ('986','BRL','Бразильский реал')


SELECT *
FROM @Tmp
ORDER BY Code