/*
ОКСМ — Общероссийский классификатор стран мира
*/

DECLARE @Tmp TABLE
(
[Code] VARCHAR(3) UNIQUE,
[ShortName] VARCHAR(255),
[FullName] VARCHAR(255),
[Alfa2] VARCHAR(2) UNIQUE,
[Alfa3] VARCHAR(3) UNIQUE
)

INSERT INTO @Tmp VALUES ('004','Афганистан','Переходное Исламское Государство Афганистан','AF','AFG')
INSERT INTO @Tmp VALUES ('008','Албания','Республика Албания','AL','ALB')
INSERT INTO @Tmp VALUES ('010','Антарктида','','AQ','ATA')
INSERT INTO @Tmp VALUES ('012','Алжир','Алжирская Народная Демократическая Республика','DZ','DZA')
INSERT INTO @Tmp VALUES ('016','Американское Самоа','','AS','ASM')
INSERT INTO @Tmp VALUES ('020','Андорра','Княжество Андорра','AD','AND')
INSERT INTO @Tmp VALUES ('024','Ангола','Республика Ангола','AO','AGO')
INSERT INTO @Tmp VALUES ('028','Антигуа и Барбуда','','AG','ATG')
INSERT INTO @Tmp VALUES ('031','Азербайджан','Республика Азербайджан','AZ','AZE')
INSERT INTO @Tmp VALUES ('032','Аргентина','Аргентинская Республика','AR','ARG')
INSERT INTO @Tmp VALUES ('036','Австралия','','AU','AUS')
INSERT INTO @Tmp VALUES ('040','Австрия','Австрийская Республика','AT','AUT')
INSERT INTO @Tmp VALUES ('044','Багамы','Содружество Багамы','BS','BHS')
INSERT INTO @Tmp VALUES ('048','Бахрейн','Королевство Бахрейн','BH','BHR')
INSERT INTO @Tmp VALUES ('050','Бангладеш','Народная Республика Бангладеш','BD','BGD')
INSERT INTO @Tmp VALUES ('051','Армения','Республика Армения','AM','ARM')
INSERT INTO @Tmp VALUES ('052','Барбадос','','BB','BRB')
INSERT INTO @Tmp VALUES ('056','Бельгия','Королевство Бельгия','BE','BEL')
INSERT INTO @Tmp VALUES ('060','Бермуды','','BM','BMU')
INSERT INTO @Tmp VALUES ('064','Бутан','Королевство Бутан','BT','BTN')
INSERT INTO @Tmp VALUES ('068','Боливия, многонациональное государство','Многонациональное Государство Боливия','BO','BOL')
INSERT INTO @Tmp VALUES ('070','Босния и Герцеговина','','BA','BIH')
INSERT INTO @Tmp VALUES ('072','Ботсвана','Республика Ботсвана','BW','BWA')
INSERT INTO @Tmp VALUES ('074','Остров Буве','','BV','BVT')
INSERT INTO @Tmp VALUES ('076','Бразилия','Федеративная Республика Бразилия','BR','BRA')
INSERT INTO @Tmp VALUES ('084','Белиз','','BZ','BLZ')
INSERT INTO @Tmp VALUES ('086','Британская территория в Индийском океане','','IO','IOT')
INSERT INTO @Tmp VALUES ('090','Соломоновы Острова','','SB','SLB')
INSERT INTO @Tmp VALUES ('092','Виргинские Острова (Британские)','','VG','VGB')
INSERT INTO @Tmp VALUES ('096','Бруней-Даруссалам','','BN','BRN')
INSERT INTO @Tmp VALUES ('100','Болгария','Республика Болгария','BG','BGR')
INSERT INTO @Tmp VALUES ('104','Мьянма','Республика Союза Мьянма','MM','MMR')
INSERT INTO @Tmp VALUES ('108','Бурунди','Республика Бурунди','BI','BDI')
INSERT INTO @Tmp VALUES ('112','Беларусь','Республика Беларусь','BY','BLR')
INSERT INTO @Tmp VALUES ('116','Камбоджа','Королевство Камбоджа','KH','KHM')
INSERT INTO @Tmp VALUES ('120','Камерун','Республика Камерун','CM','CMR')
INSERT INTO @Tmp VALUES ('124','Канада','','CA','CAN')
INSERT INTO @Tmp VALUES ('132','Кабо-Верде','Республика Кабо-Верде','CV','CPV')
INSERT INTO @Tmp VALUES ('136','Острова Кайман','','KY','CYM')
INSERT INTO @Tmp VALUES ('140','Центрально-Африканская Республика','','CF','CAF')
INSERT INTO @Tmp VALUES ('144','Шри-Ланка','Демократическая Социалистическая Республика Шри-Ланка','LK','LKA')
INSERT INTO @Tmp VALUES ('148','Чад','Республика Чад','TD','TCD')
INSERT INTO @Tmp VALUES ('152','Чили','Республика Чили','CL','CHL')
INSERT INTO @Tmp VALUES ('156','Китай','Китайская Народная Республика','CN','CHN')
INSERT INTO @Tmp VALUES ('158','Тайвань (Китай)','','TW','TWN')
INSERT INTO @Tmp VALUES ('162','Остров Рождества','','CX','CXR')
INSERT INTO @Tmp VALUES ('166','Кокосовые (Килинг) острова','','CC','CCK')
INSERT INTO @Tmp VALUES ('170','Колумбия','Республика Колумбия','CO','COL')
INSERT INTO @Tmp VALUES ('174','Коморы','Союз Коморы','KM','COM')
INSERT INTO @Tmp VALUES ('175','Майотта','','YT','MYT')
INSERT INTO @Tmp VALUES ('178','Конго','Республика Конго','CG','COG')
INSERT INTO @Tmp VALUES ('180','Конго, Демократическая Республика','Демократическая Республика Конго','CD','COD')
INSERT INTO @Tmp VALUES ('184','Острова Кука','','CK','COK')
INSERT INTO @Tmp VALUES ('188','Коста-рика','Республика Коста-Рика','CR','CRI')
INSERT INTO @Tmp VALUES ('191','Хорватия','Республика Хорватия','HR','HRV')
INSERT INTO @Tmp VALUES ('192','Куба','Республика Куба','CU','CUB')
INSERT INTO @Tmp VALUES ('196','Кипр','Республика Кипр','CY','CYP')
INSERT INTO @Tmp VALUES ('203','Чехия','Чешская Республика','CZ','CZE')
INSERT INTO @Tmp VALUES ('204','Бенин','Республика Бенин','BJ','BEN')
INSERT INTO @Tmp VALUES ('208','Дания','Королевство Дания','DK','DNK')
INSERT INTO @Tmp VALUES ('212','Доминика','Содружество Доминики','DM','DMA')
INSERT INTO @Tmp VALUES ('214','Доминиканская Республика','','DO','DOM')
INSERT INTO @Tmp VALUES ('218','Эквадор','Республика Эквадор','EC','ECU')
INSERT INTO @Tmp VALUES ('222','Эль-Сальвадор','Республика Эль-Сальвадор','SV','SLV')
INSERT INTO @Tmp VALUES ('226','Экваториальная Гвинея','Республика Экваториальная Гвинея','GQ','GNQ')
INSERT INTO @Tmp VALUES ('231','Эфиопия','Федеративная Демократическая Республика Эфиопия','ET','ETH')
INSERT INTO @Tmp VALUES ('232','Эритрея','Государство Эритрея','ER','ERI')
INSERT INTO @Tmp VALUES ('233','Эстония','Эстонская Республика','EE','EST')
INSERT INTO @Tmp VALUES ('234','Фарерские Острова','','FO','FRO')
INSERT INTO @Tmp VALUES ('238','Фолклендские Острова (Мальвинские)','','FK','FLK')
INSERT INTO @Tmp VALUES ('239','Южная Джорджия и Южные Сандвичевы Острова','','GS','SGS')
INSERT INTO @Tmp VALUES ('242','Фиджи','Республика Фиджи','FJ','FJI')
INSERT INTO @Tmp VALUES ('246','Финляндия','Финляндская Республика','FI','FIN')
INSERT INTO @Tmp VALUES ('248','Эландские Острова','','AX','ALA')
INSERT INTO @Tmp VALUES ('250','Франция','Французская Республика','FR','FRA')
INSERT INTO @Tmp VALUES ('254','Французская Гвиана','','GF','GUF')
INSERT INTO @Tmp VALUES ('258','Французская Полинезия','','PF','PYF')
INSERT INTO @Tmp VALUES ('260','Французские Южные территории','','TF','ATF')
INSERT INTO @Tmp VALUES ('262','Джибути','Республика Джибути','DJ','DJI')
INSERT INTO @Tmp VALUES ('266','Габон','Габонская Республика','GA','GAB')
INSERT INTO @Tmp VALUES ('268','Грузия','','GE','GEO')
INSERT INTO @Tmp VALUES ('270','Гамбия','Исламская Республика Гамбия','GM','GMB')
INSERT INTO @Tmp VALUES ('275','Палестина, Государство','Государство Палестина','PS','PSE')
INSERT INTO @Tmp VALUES ('276','Германия','Федеративная Республика Германия','DE','DEU')
INSERT INTO @Tmp VALUES ('288','Гана','Республика Гана','GH','GHA')
INSERT INTO @Tmp VALUES ('292','Гибралтар','','GI','GIB')
INSERT INTO @Tmp VALUES ('296','Кирибати','Республика Кирибати','KI','KIR')
INSERT INTO @Tmp VALUES ('300','Греция','Греческая Республика','GR','GRC')
INSERT INTO @Tmp VALUES ('304','Гренландия','','GL','GRL')
INSERT INTO @Tmp VALUES ('308','Гренада','','GD','GRD')
INSERT INTO @Tmp VALUES ('312','Гваделупа','','GP','GLP')
INSERT INTO @Tmp VALUES ('316','Гуам','','GU','GUM')
INSERT INTO @Tmp VALUES ('320','Гватемала','Республика Гватемала','GT','GTM')
INSERT INTO @Tmp VALUES ('324','Гвинея','Гвинейская Республика','GN','GIN')
INSERT INTO @Tmp VALUES ('328','Гайана','Кооперативная Республика Гайана','GY','GUY')
INSERT INTO @Tmp VALUES ('332','Гаити','Республика Гаити','HT','HTI')
INSERT INTO @Tmp VALUES ('334','Остров Херд и острова Макдональд','','HM','HMD')
INSERT INTO @Tmp VALUES ('336','Папский Престол (Государство-город Ватикан)','','VA','VAT')
INSERT INTO @Tmp VALUES ('340','Гондурас','Республика Гондурас','HN','HND')
INSERT INTO @Tmp VALUES ('344','Гонконг','Специальный административный регион Китая Гонконг','HK','HKG')
INSERT INTO @Tmp VALUES ('348','Венгрия','Венгрия','HU','HUN')
INSERT INTO @Tmp VALUES ('352','Исландия','Республика Исландия','IS','ISL')
INSERT INTO @Tmp VALUES ('356','Индия','Республика Индия','IN','IND')
INSERT INTO @Tmp VALUES ('360','Индонезия','Республика Индонезия','ID','IDN')
INSERT INTO @Tmp VALUES ('364','Иран (Исламская Республика)','','IR','IRN')
INSERT INTO @Tmp VALUES ('368','Ирак','Республика Ирак','IQ','IRQ')
INSERT INTO @Tmp VALUES ('372','Ирландия','','IE','IRL')
INSERT INTO @Tmp VALUES ('376','Израиль','Государство Израиль','IL','ISR')
INSERT INTO @Tmp VALUES ('380','Италия','Итальянская Республика','IT','ITA')
INSERT INTO @Tmp VALUES ('384','Кот д`Ивуар','Республика Кот д`Ивуар','CI','CIV')
INSERT INTO @Tmp VALUES ('388','Ямайка','','JM','JAM')
INSERT INTO @Tmp VALUES ('392','Япония','','JP','JPN')
INSERT INTO @Tmp VALUES ('398','Казахстан','Республика Казахстан','KZ','KAZ')
INSERT INTO @Tmp VALUES ('400','Иордания','Иорданское Хашимитское Королевство','JO','JOR')
INSERT INTO @Tmp VALUES ('404','Кения','Республика Кения','KE','KEN')
INSERT INTO @Tmp VALUES ('408','Корея, Народно-Демократическая Республика','Корейская Народно-Демократическая Республика','KP','PRK')
INSERT INTO @Tmp VALUES ('410','Корея, Республика','Республика Корея','KR','KOR')
INSERT INTO @Tmp VALUES ('414','Кувейт','Государство Кувейт','KW','KWT')
INSERT INTO @Tmp VALUES ('417','Киргизия','Киргизская Республика','KG','KGZ')
INSERT INTO @Tmp VALUES ('418','Лаосская Народно-Демократическая Республика','','LA','LAO')
INSERT INTO @Tmp VALUES ('422','Ливан','Ливанская Республика','LB','LBN')
INSERT INTO @Tmp VALUES ('426','Лесото','Королевство Лесото','LS','LSO')
INSERT INTO @Tmp VALUES ('428','Латвия','Латвийская Республика','LV','LVA')
INSERT INTO @Tmp VALUES ('430','Либерия','Республика Либерия','LR','LBR')
INSERT INTO @Tmp VALUES ('434','Ливия','Государство Ливия','LY','LBY')
INSERT INTO @Tmp VALUES ('438','Лихтенштейн','Княжество Лихтенштейн','LI','LIE')
INSERT INTO @Tmp VALUES ('440','Литва','Литовская Республика','LT','LTU')
INSERT INTO @Tmp VALUES ('442','Люксембург','Великое Герцогство Люксембург','LU','LUX')
INSERT INTO @Tmp VALUES ('446','Макао','Специальный административный регион Китая Макао','MO','MAC')
INSERT INTO @Tmp VALUES ('450','Мадагаскар','Республика Мадагаскар','MG','MDG')
INSERT INTO @Tmp VALUES ('454','Малави','Республика Малави','MW','MWI')
INSERT INTO @Tmp VALUES ('458','Малайзия','','MY','MYS')
INSERT INTO @Tmp VALUES ('462','Мальдивы','Мальдивская Республика','MV','MDV')
INSERT INTO @Tmp VALUES ('466','Мали','Республика Мали','ML','MLI')
INSERT INTO @Tmp VALUES ('470','Мальта','Республика Мальта','MT','MLT')
INSERT INTO @Tmp VALUES ('474','Мартиника','','MQ','MTQ')
INSERT INTO @Tmp VALUES ('478','Мавритания','Исламская Республика Мавритания','MR','MRT')
INSERT INTO @Tmp VALUES ('480','Маврикий','Республика Маврикий','MU','MUS')
INSERT INTO @Tmp VALUES ('484','Мексика','Мексиканские Соединенные Штаты','MX','MEX')
INSERT INTO @Tmp VALUES ('492','Монако','Княжество Монако','MC','MCO')
INSERT INTO @Tmp VALUES ('496','Монголия','','MN','MNG')
INSERT INTO @Tmp VALUES ('498','Молдова, Республика','Республика Молдова','MD','MDA')
INSERT INTO @Tmp VALUES ('499','Черногория','','ME','MNE')
INSERT INTO @Tmp VALUES ('500','Монтсеррат','','MS','MSR')
INSERT INTO @Tmp VALUES ('504','Марокко','Королевство Марокко','MA','MAR')
INSERT INTO @Tmp VALUES ('508','Мозамбик','Республика Мозамбик','MZ','MOZ')
INSERT INTO @Tmp VALUES ('512','Оман','Султанат Оман','OM','OMN')
INSERT INTO @Tmp VALUES ('516','Намибия','Республика Намибия','NA','NAM')
INSERT INTO @Tmp VALUES ('520','Науру','Республика Науру','NR','NRU')
INSERT INTO @Tmp VALUES ('524','Непал','Федеративная Демократическая Республика Непал','NP','NPL')
INSERT INTO @Tmp VALUES ('528','Нидерланды','Королевство Нидерландов','NL','NLD')
INSERT INTO @Tmp VALUES ('531','Кюрасао','','CW','CUW')
INSERT INTO @Tmp VALUES ('533','Аруба','','AW','ABW')
INSERT INTO @Tmp VALUES ('534','Сен-Мартен (нидерландская часть)','','SX','SXM')
INSERT INTO @Tmp VALUES ('535','Бонэйр, Синт-Эстатиус и Саба','','BQ','BES')
INSERT INTO @Tmp VALUES ('540','Новая Каледония','','NC','NCL')
INSERT INTO @Tmp VALUES ('548','Вануату','Республика Вануату','VU','VUT')
INSERT INTO @Tmp VALUES ('554','Новая Зеландия','','NZ','NZL')
INSERT INTO @Tmp VALUES ('558','Никарагуа','Республика Никарагуа','NI','NIC')
INSERT INTO @Tmp VALUES ('562','Нигер','Республика Нигер','NE','NER')
INSERT INTO @Tmp VALUES ('566','Нигерия','Федеративная Республика Нигерия','NG','NGA')
INSERT INTO @Tmp VALUES ('570','Ниуэ','Ниуэ','NU','NIU')
INSERT INTO @Tmp VALUES ('574','Остров Норфолк','','NF','NFK')
INSERT INTO @Tmp VALUES ('578','Норвегия','Королевство Норвегия','NO','NOR')
INSERT INTO @Tmp VALUES ('580','Северные Марианские Острова','Содружество Северных Марианских островов','MP','MNP')
INSERT INTO @Tmp VALUES ('581','Малые Тихоокеанские Отдаленные острова Соединенных Штатов','','UM','UMI')
INSERT INTO @Tmp VALUES ('583','Микронезия, Федеративные Штаты','Федеративные Штаты Микронезии','FM','FSM')
INSERT INTO @Tmp VALUES ('584','Маршалловы Острова','Республика Маршалловы Острова','MH','MHL')
INSERT INTO @Tmp VALUES ('585','Палау','Республика Палау','PW','PLW')
INSERT INTO @Tmp VALUES ('586','Пакистан','Исламская Республика Пакистан','PK','PAK')
INSERT INTO @Tmp VALUES ('591','Панама','Республика Панама','PA','PAN')
INSERT INTO @Tmp VALUES ('598','Папуа Новая Гвинея','Независимое Государство Папуа Новая Гвинея','PG','PNG')
INSERT INTO @Tmp VALUES ('600','Парагвай','Республика Парагвай','PY','PRY')
INSERT INTO @Tmp VALUES ('604','Перу','Республика Перу','PE','PER')
INSERT INTO @Tmp VALUES ('608','Филиппины','Республика Филиппины','PH','PHL')
INSERT INTO @Tmp VALUES ('612','Питкерн','','PN','PCN')
INSERT INTO @Tmp VALUES ('616','Польша','Республика Польша','PL','POL')
INSERT INTO @Tmp VALUES ('620','Португалия','Португальская Республика','PT','PRT')
INSERT INTO @Tmp VALUES ('624','Гвинея-Бисау','Республика Гвинея-Бисау','GW','GNB')
INSERT INTO @Tmp VALUES ('626','Тимор-Лесте','Демократическая Республика Тимор-Лесте','TL','TLS')
INSERT INTO @Tmp VALUES ('630','Пуэрто-Рико','','PR','PRI')
INSERT INTO @Tmp VALUES ('634','Катар','Государство Катар','QA','QAT')
INSERT INTO @Tmp VALUES ('638','Реюньон','','RE','REU')
INSERT INTO @Tmp VALUES ('642','Румыния','','RO','ROU')
INSERT INTO @Tmp VALUES ('643','Россия','Российская Федерация','RU','RUS')
INSERT INTO @Tmp VALUES ('646','Руанда','Руандийская Республика','RW','RWA')
INSERT INTO @Tmp VALUES ('652','Сен-Бартелеми','','BL','BLM')
INSERT INTO @Tmp VALUES ('654','Святая Елена, Остров Вознесения, Тристан-да-Кунья','','SH','SHN')
INSERT INTO @Tmp VALUES ('659','Сент-Китс и Невис','','KN','KNA')
INSERT INTO @Tmp VALUES ('660','Ангилья','','AI','AIA')
INSERT INTO @Tmp VALUES ('662','Сент-Люсия','','LC','LCA')
INSERT INTO @Tmp VALUES ('663','Сен-Мартен (французская часть)','','MF','MAF')
INSERT INTO @Tmp VALUES ('666','Сент-Пьер и Микелон','','PM','SPM')
INSERT INTO @Tmp VALUES ('670','Сент-Винсент и Гренадины','','VC','VCT')
INSERT INTO @Tmp VALUES ('674','Сан-Марино','Республика Сан-Марино','SM','SMR')
INSERT INTO @Tmp VALUES ('678','Сан-Томе и Принсипи','Демократическая Республика Сан-Томе и Принсипи','ST','STP')
INSERT INTO @Tmp VALUES ('682','Саудовская Аравия','Королевство Саудовская Аравия','SA','SAU')
INSERT INTO @Tmp VALUES ('686','Сенегал','Республика Сенегал','SN','SEN')
INSERT INTO @Tmp VALUES ('688','Сербия','Республика Сербия','RS','SRB')
INSERT INTO @Tmp VALUES ('690','Сейшелы','Республика Сейшелы','SC','SYC')
INSERT INTO @Tmp VALUES ('694','Сьерра-Леоне','Республика Сьерра-Леоне','SL','SLE')
INSERT INTO @Tmp VALUES ('702','Сингапур','Республика Сингапур','SG','SGP')
INSERT INTO @Tmp VALUES ('703','Словакия','Словацкая Республика','SK','SVK')
INSERT INTO @Tmp VALUES ('704','Вьетнам','Социалистическая Республика Вьетнам','VN','VNM')
INSERT INTO @Tmp VALUES ('705','Словения','Республика Словения','SI','SVN')
INSERT INTO @Tmp VALUES ('706','Сомали','Федеративная Республика Сомали','SO','SOM')
INSERT INTO @Tmp VALUES ('710','Южная Африка','Южно-Африканская Республика','ZA','ZAF')
INSERT INTO @Tmp VALUES ('716','Зимбабве','Республика Зимбабве','ZW','ZWE')
INSERT INTO @Tmp VALUES ('724','Испания','Королевство Испания','ES','ESP')
INSERT INTO @Tmp VALUES ('728','Южный Судан','Республика Южный Судан','SS','SSD')
INSERT INTO @Tmp VALUES ('729','Судан','Республика Судан','SD','SDN')
INSERT INTO @Tmp VALUES ('732','Западная Сахара','','EH','ESH')
INSERT INTO @Tmp VALUES ('740','Суринам','Республика Суринам','SR','SUR')
INSERT INTO @Tmp VALUES ('744','Шпицберген и Ян Майен','','SJ','SJM')
INSERT INTO @Tmp VALUES ('748','Эсватини','Королевство Эсватини','SZ','SWZ')
INSERT INTO @Tmp VALUES ('752','Швеция','Королевство Швеция','SE','SWE')
INSERT INTO @Tmp VALUES ('756','Швейцария','Швейцарская Конфедерация','CH','CHE')
INSERT INTO @Tmp VALUES ('760','Сирийская Арабская Республика','','SY','SYR')
INSERT INTO @Tmp VALUES ('762','Таджикистан','Республика Таджикистан','TJ','TJK')
INSERT INTO @Tmp VALUES ('764','Таиланд','Королевство Таиланд','TH','THA')
INSERT INTO @Tmp VALUES ('768','Того','Тоголезская Республика','TG','TGO')
INSERT INTO @Tmp VALUES ('772','Токелау','','TK','TKL')
INSERT INTO @Tmp VALUES ('776','Тонга','Королевство Тонга','TO','TON')
INSERT INTO @Tmp VALUES ('780','Тринидад и Тобаго','Республика Тринидад и Тобаго','TT','TTO')
INSERT INTO @Tmp VALUES ('784','Объединенные Арабские Эмираты','','AE','ARE')
INSERT INTO @Tmp VALUES ('788','Тунис','Тунисская Республика','TN','TUN')
INSERT INTO @Tmp VALUES ('792','Турция','Турецкая Республика','TR','TUR')
INSERT INTO @Tmp VALUES ('795','Туркменистан','','TM','TKM')
INSERT INTO @Tmp VALUES ('796','Острова Теркс и Кайкос','','TC','TCA')
INSERT INTO @Tmp VALUES ('798','Тувалу','','TV','TUV')
INSERT INTO @Tmp VALUES ('800','Уганда','Республика Уганда','UG','UGA')
INSERT INTO @Tmp VALUES ('804','Украина','','UA','UKR')
INSERT INTO @Tmp VALUES ('807','Северная Македония','Республика Северная Македония','MK','MKD')
INSERT INTO @Tmp VALUES ('818','Египет','Арабская Республика Египет','EG','EGY')
INSERT INTO @Tmp VALUES ('826','Соединенное Королевство','Соединенное Королевство Великобритании и Северной Ирландии','GB','GBR')
INSERT INTO @Tmp VALUES ('831','Гернси','','GG','GGY')
INSERT INTO @Tmp VALUES ('832','Джерси','','JE','JEY')
INSERT INTO @Tmp VALUES ('833','Остров Мэн','','IM','IMN')
INSERT INTO @Tmp VALUES ('834','Танзания, Объединенная Республика','Объединенная Республика Танзания','TZ','TZA')
INSERT INTO @Tmp VALUES ('840','Соединенные Штаты','Соединенные Штаты Америки','US','USA')
INSERT INTO @Tmp VALUES ('850','Виргинские Острова (США)','','VI','VIR')
INSERT INTO @Tmp VALUES ('854','Буркина-Фасо','','BF','BFA')
INSERT INTO @Tmp VALUES ('858','Уругвай','Восточная Республика Уругвай','UY','URY')
INSERT INTO @Tmp VALUES ('860','Узбекистан','Республика Узбекистан','UZ','UZB')
INSERT INTO @Tmp VALUES ('862','Венесуэла (Боливарианская Республика)','','VE','VEN')
INSERT INTO @Tmp VALUES ('876','Уоллис и Футуна','','WF','WLF')
INSERT INTO @Tmp VALUES ('882','Самоа','Независимое Государство Самоа','WS','WSM')
INSERT INTO @Tmp VALUES ('887','Йемен','Йеменская Республика','YE','YEM')
INSERT INTO @Tmp VALUES ('894','Замбия','Республика Замбия','ZM','ZMB')
INSERT INTO @Tmp VALUES ('895','Абхазия','Республика Абхазия','AB','ABH')
INSERT INTO @Tmp VALUES ('896','Южная Осетия','Республика Южная Осетия','OS','OST')
INSERT INTO @Tmp VALUES ('998','Международная организация','Международная организация','98','998')
INSERT INTO @Tmp VALUES ('999','Лицо без гражданства','Лицо без гражданства','99','999')

UPDATE @Tmp
SET FullName=[ShortName]
WHERE ISNULL(FullName,'') = ''

SELECT *
FROM @Tmp
ORDER BY Code
