DECLARE @Tmp TABLE
(
[Code] VARCHAR(3) UNIQUE,
[FullName] VARCHAR(255)
)

INSERT INTO @Tmp VALUES ('01','Республика Адыгея (Адыгея)')
INSERT INTO @Tmp VALUES ('02','Республика Башкортостан')
INSERT INTO @Tmp VALUES ('03','Республика Бурятия')
INSERT INTO @Tmp VALUES ('04','Республика Алтай')
INSERT INTO @Tmp VALUES ('05','Республика Дагестан')
INSERT INTO @Tmp VALUES ('06','Республика Ингушетия')
INSERT INTO @Tmp VALUES ('07','Кабардино-Балкарская Республика')
INSERT INTO @Tmp VALUES ('08','Республика Калмыкия')
INSERT INTO @Tmp VALUES ('09','Карачаево-Черкесская Республика')
INSERT INTO @Tmp VALUES ('10','Республика Карелия')
INSERT INTO @Tmp VALUES ('11','Республика Коми')
INSERT INTO @Tmp VALUES ('12','Республика Марий Эл')
INSERT INTO @Tmp VALUES ('13','Республика Мордовия')
INSERT INTO @Tmp VALUES ('14','Республика Саха (Якутия)')
INSERT INTO @Tmp VALUES ('15','Республика Северная Осетия - Алания')
INSERT INTO @Tmp VALUES ('16','Республика Татарстан (Татарстан)')
INSERT INTO @Tmp VALUES ('17','Республика Тыва')
INSERT INTO @Tmp VALUES ('18','Удмуртская Республика')
INSERT INTO @Tmp VALUES ('19','Республика Хакасия')
INSERT INTO @Tmp VALUES ('20','Чеченская Республика')
INSERT INTO @Tmp VALUES ('21','Чувашская Республика - Чувашия')
INSERT INTO @Tmp VALUES ('22','Алтайский край')
INSERT INTO @Tmp VALUES ('23','Краснодарский край')
INSERT INTO @Tmp VALUES ('24','Красноярский край')
INSERT INTO @Tmp VALUES ('25','Приморский край')
INSERT INTO @Tmp VALUES ('26','Ставропольский край')
INSERT INTO @Tmp VALUES ('27','Хабаровский край')
INSERT INTO @Tmp VALUES ('28','Амурская область')
INSERT INTO @Tmp VALUES ('29','Архангельская область')
INSERT INTO @Tmp VALUES ('30','Астраханская область')
INSERT INTO @Tmp VALUES ('31','Белгородская область')
INSERT INTO @Tmp VALUES ('32','Брянская область')
INSERT INTO @Tmp VALUES ('33','Владимирская область')
INSERT INTO @Tmp VALUES ('34','Волгоградская область')
INSERT INTO @Tmp VALUES ('35','Вологодская область')
INSERT INTO @Tmp VALUES ('36','Воронежская область')
INSERT INTO @Tmp VALUES ('37','Ивановская область')
INSERT INTO @Tmp VALUES ('38','Иркутская область')
INSERT INTO @Tmp VALUES ('39','Калининградская область')
INSERT INTO @Tmp VALUES ('40','Калужская область')
INSERT INTO @Tmp VALUES ('41','Камчатский край')
INSERT INTO @Tmp VALUES ('42','Кемеровская область - Кузбасс')
INSERT INTO @Tmp VALUES ('43','Кировская область')
INSERT INTO @Tmp VALUES ('44','Костромская область')
INSERT INTO @Tmp VALUES ('45','Курганская область')
INSERT INTO @Tmp VALUES ('46','Курская область')
INSERT INTO @Tmp VALUES ('47','Ленинградская область')
INSERT INTO @Tmp VALUES ('48','Липецкая область')
INSERT INTO @Tmp VALUES ('49','Магаданская область')
INSERT INTO @Tmp VALUES ('50','Московская область')
INSERT INTO @Tmp VALUES ('51','Мурманская область')
INSERT INTO @Tmp VALUES ('52','Нижегородская область')
INSERT INTO @Tmp VALUES ('53','Новгородская область')
INSERT INTO @Tmp VALUES ('54','Новосибирская область')
INSERT INTO @Tmp VALUES ('55','Омская область')
INSERT INTO @Tmp VALUES ('56','Оренбургская область')
INSERT INTO @Tmp VALUES ('57','Орловская область')
INSERT INTO @Tmp VALUES ('58','Пензенская область')
INSERT INTO @Tmp VALUES ('59','Пермский край')
INSERT INTO @Tmp VALUES ('60','Псковская область')
INSERT INTO @Tmp VALUES ('61','Ростовская область')
INSERT INTO @Tmp VALUES ('62','Рязанская область')
INSERT INTO @Tmp VALUES ('63','Самарская область')
INSERT INTO @Tmp VALUES ('64','Саратовская область')
INSERT INTO @Tmp VALUES ('65','Сахалинская область')
INSERT INTO @Tmp VALUES ('66','Свердловская область')
INSERT INTO @Tmp VALUES ('67','Смоленская область')
INSERT INTO @Tmp VALUES ('68','Тамбовская область')
INSERT INTO @Tmp VALUES ('69','Тверская область')
INSERT INTO @Tmp VALUES ('70','Томская область')
INSERT INTO @Tmp VALUES ('71','Тульская область')
INSERT INTO @Tmp VALUES ('72','Тюменская область')
INSERT INTO @Tmp VALUES ('73','Ульяновская область')
INSERT INTO @Tmp VALUES ('74','Челябинская область')
INSERT INTO @Tmp VALUES ('75','Забайкальский край')
INSERT INTO @Tmp VALUES ('76','Ярославская область')
INSERT INTO @Tmp VALUES ('77','Г.Москва')
INSERT INTO @Tmp VALUES ('78','Г.Санкт-Петербург')
INSERT INTO @Tmp VALUES ('79','Еврейская автономная область')
INSERT INTO @Tmp VALUES ('83','Ненецкий автономный округ')
INSERT INTO @Tmp VALUES ('86','Ханты-Мансийский автономный округ - Югра')
INSERT INTO @Tmp VALUES ('87','Чукотский автономный округ')
INSERT INTO @Tmp VALUES ('89','Ямало-Ненецкий автономный округ')
INSERT INTO @Tmp VALUES ('91','Республика Крым')
INSERT INTO @Tmp VALUES ('92','Г.Севастополь')
INSERT INTO @Tmp VALUES ('99','Иные территории,включая город и космодром Байконур')


SELECT *
FROM @Tmp
ORDER BY Code
